name: yearn-boosted-staker

plugins:
  - name: solidity
  - name: ens
  - name: etherscan
  - name: foundry
  - name: alchemy

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity: 
  import_remapping:
    - "@openzeppelin/contracts/=OpenZeppelin/4.9.3"

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  base_fee: 0
  priority_fee: 0
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy